#!/usr/bin/env python3
"""Inline every config the engine needs into a single TS module for browser bundling."""
import json, os
C = 'config'
def load(f): return json.load(open(os.path.join(C, f)))

# The panel is large; the UI only needs the seed window around 2026Q2.
panel = load('panel_quarterly.json')
i0 = panel['periods'].index('2026Q2')
lo, hi = i0 - 6, i0 + 1
slim = {'periods': panel['periods'][lo:hi],
        'series': {k: v[lo:hi] for k, v in panel['series'].items()}}
supply = load('supply.json')
slim_supply = {'alpha': supply['alpha'], 'delta_quarterly': supply['delta_quarterly'],
               'periods': supply['periods'][lo:hi],
               'K': supply['K'][lo:hi], 'L': supply['L'][lo:hi], 'TFP': supply['TFP'][lo:hi],
               'potential_pf': supply['potential_pf'][lo:hi], 'gap_pf': supply['gap_pf'][lo:hi]}

out = {
  'panel': slim, 'supply': slim_supply, 'panelOffset': lo,
  'coalitions': load('coalitions.json'),
  'policies': load('policies.json'),
  'events': load('events.json'),
  'playability': load('playability.json'),
  'set': load('set_history.json'),
}
os.makedirs('engine/src/gen', exist_ok=True)
with open('engine/src/gen/data.ts', 'w') as f:
    f.write('// GENERATED by scripts/build_ui_data.py — do not edit.\n')
    f.write('export const DATA = ' + json.dumps(out, separators=(',', ':'), ensure_ascii=False) + ' as const;\n')
print('engine/src/gen/data.ts  %.1f KB' % (os.path.getsize('engine/src/gen/data.ts')/1024))
